catalog/urls.py
from django.urls import path
from .views import *


app_name = 'catalog'


urlpatterns = [
    path('', shop, name='shop'),
    path('like/<int:item_id>/', like_item, name='like_item'),
    path('favorite/<int:item_id>/', favorite_item, name='favorite_item'),
    path('exchange/<int:received_item_id>/', exchange, name='exchange'),
    path('send_offer/<int:received_item_id>/<int:sent_item_id>/', send_exchange, name='send_offer'),
    path('<slug:item_slug>/<int:item_id>/', item_detail, name='item_detail'),
    path('add_item/', add_item, name='add_item'),
    path('delete_item/<int:obj_id>', delete_obj, name='delete_item'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('change_exchange/<int:exchange_id>/<str:action>', change_exchange, name='change_exchange'),
    path('add_message/', contact, name='add_message'),
    path('search/', search_view, name='search'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:room_name>/', views.chat_room, name='chat_room'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from catalog.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('user.urls', namespace='users')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import *


app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user-profile/<str:username>/<int:user_id>/', user_details, name='user_profile'),
    path('add_comment/<int:user_id>/', add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('positive/<int:user_id>', user_positive_rating, name='positive_rating'),
    path('negative/<int:user_id>', user_negative_rating, name='negative_rating'),
    path('logout/', logout, name='logout'),

]

user/models.py
from typing import Self
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    user_positive_rating = models.ManyToManyField('self', blank=True)
    user_negative_rating = models.ManyToManyField('self', blank=True)
    amount_of_deals = models.IntegerField(default=0) 
    active_deals = models.IntegerField(default=0)
    ip_address  = models.GenericIPAddressField(blank=True, null=True)
    address = models.CharField(max_length=200, null=True, blank=True)





    def get_absolute_url(self):
        return reverse("users:user_profile", args=[self.username, self.pk])





class UserComments(models.Model):
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Comment by {} on {}".format(self.user, self.item)

user/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)
from user.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "User Name*"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    class Meta:
        model = User
        fields = ("username", "password")


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите имя"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите фамилию"})
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={"placeholder": "Введите Email"})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите имя пользователя"})
    )
    password1 = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите пароль"})
    )
    password2 = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Подтвердите пароль"})
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "password1",
            "password2",
            "ip_address",
        )


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={"class": "form-control py-4"})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True})
    )
    image = forms.ImageField(
        widget=forms.FileInput(attrs={"class": "custom-file-input"}), required=False
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    address = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "image", "username", "email", "phone_number", "address")

user/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.urls import reverse
from datetime import datetime, timedelta
from user.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from catalog.models import Item, Exchange
from user.models import User, UserComments

# Create your views here.


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("index"))
    else:
        form = UserLoginForm()

    context = {"login_form": form}
    return render(request, "user/signin.html", context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.ip_address = request.META.get("REMOTE_ADDR")
            user.save()
            messages.success(request, "Регистрация прошла успешно!")
            return HttpResponseRedirect(reverse("users:login"))
    else:
        form = UserRegistrationForm()
    context = {"reg_form": form}

    return render(request, "user/signin.html", context)


@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(
            instance=request.user, data=request.POST, files=request.FILES
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserProfileForm(instance=request.user)
    items = Item.objects.filter(
        active=False, deactivate_date__lt=datetime.now() - timedelta(days=30)
    )
    for item in items:
        item.delete()
    context = {
        "form": form,
        "my_items": Item.objects.filter(seller=request.user, active=True),
        "favorites": Item.objects.filter(favorites=request.user, active=True).exclude(
            seller=request.user
        ),
        "accepted_exchanges": Exchange.objects.filter(Q(received_item__seller=request.user) | Q(sent_item__seller=request.user)),
        "waiting_status": Exchange.objects.filter(received_item__seller=request.user, status="waiting")
    }
    return render(request, "user/checkout.html", context)


def user_details(request, username=None, user_id=None):
    user = get_object_or_404(User, username=username, pk=user_id)
    user_items = Item.objects.filter(seller=user, active=True)
    context = {"user": user, "user_items": user_items}
    return render(request, "user/profile_for_users.html", context)


@login_required
def add_comment(request, user_id=None):
    user = get_object_or_404(User, pk=user_id)
    if request.method == "POST" and request.user.is_authenticated:
        user_review = request.POST.get("user_review")
        if user_review:
            UserComments.objects.create(
                from_user=request.user, to_user=user, body=user_review
            )
            messages.success(request, "Ваше отзыв доставлено")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def delete_comment(request, comment_id):
    obj = get_object_or_404(UserComments, pk=comment_id)
    if obj.from_user == request.user:
        obj.delete()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def user_positive_rating(request, user_id):
    user = get_object_or_404(User, id=user_id)
    current_user = request.user

    if current_user in user.user_positive_rating.all():
        user.user_positive_rating.remove(current_user)
    else:
        if current_user in user.user_negative_rating.all():
            user.user_negative_rating.remove(current_user)
        user.user_positive_rating.add(current_user)

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def user_negative_rating(request, user_id):
    user = get_object_or_404(User, id=user_id)
    current_user = request.user

    if current_user in user.user_negative_rating.all():
        user.user_negative_rating.remove(current_user)
    else:
        if current_user in user.user_positive_rating.all():
            user.user_positive_rating.remove(current_user)
        user.user_negative_rating.add(current_user)

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

user/templates/user/profile_for_users.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'index' %}">Домой</a>
                    <a class="breadcrumb-item text-dark" href="{% url "catalog:shop" %}">Каталог</a>
                    <span class="breadcrumb-item active">Профиль</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary text-primary pr-3">Информация пользователя</span></h5>
    
                
                <div class="bg-light p-30 mb-5">
                    <div class="row">
                        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                            <div class="product-item bg-light mb-4">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="{% if user.image %} {{ user.image.url }}  {% else %} {% static 'img/default_avatar.jpg' %} {% endif %}" alt="">
                                </div>
                                {% if user.is_authenticated %}
                                <div class="input-group quantity mr-3" style="width: 130px; padding: 5px; padding-left: 25px;">
                                    <p class="align-middle">{{user.user_positive_rating.count}}</p>
                                    {% if request.user in user.user_positive_rating.all %}
                                            <a class="btn btn-outline-dark btn-square " href="{% url 'users:positive_rating' user_id=user.id  %}"><i class="fa fa-arrow-alt-circle-up"></i></a>
                                            {% else %}
                                            <a class="btn btn-outline-dark btn-square" href="{% url 'users:positive_rating' user_id=user.id  %}"><i class="far fa-arrow-alt-circle-up"></i></a>
                                            {% endif %}
                                            {% if request.user in user.user_negative_rating.all %}
                                            <a class="btn btn-outline-dark btn-square" href="{% url 'users:negative_rating' user_id=user.id  %}"><i class="fa fa-arrow-alt-circle-down"></i></a>
                                            {% else %}
                                            <a class="btn btn-outline-dark btn-square" href="{% url 'users:negative_rating' user_id=user.id  %}"><i class="far fa-arrow-alt-circle-down"></i></a>
                                            {% endif %}
                                            <p class="align-middle">{{user.user_negative_rating.count}}</p>
                                        </div>
                                        {% endif %}
                            </div>
                        </div>
                    <div>
                        <div class="col-md-6 form-group">
                            <label>Имя пользователя</label>
                            <strong>{{ user.username }}</strong>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Имя</label>
                            <strong>{{ user.first_name }}</strong>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Фамилия</label>
                            <strong>{{ user.last_name }}</strong>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Номар телефона</label>
                            <strong>{{ user.phone_number }}</strong>
                        </div>            
                        <div class="col-md-6 form-group">
                            <label>Адрес</label>
                            <strong>{{ user.address }}</strong>
                        </div>
                    </div>
                </div>
                </div>
                <div class="collapse mb-5 show ">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary text-primary pr-3">Лоты и Отзывы</span></h5>
                    <div class="row px-xl-5">
                        <div class="col">
                            <div class="bg-light p-30">
                                <div class="nav nav-tabs mb-4">
                                    <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Лоты пользователя</a>
                                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Отзыв</a>
                                </div>
                                <div class="tab-content">
                                    <div class="tab-pane fade show active" id="tab-pane-1">
                                        <div class="pre-scrollable">
                                        <table class="table table-light table-borderless table-hover text-center mb-0">
                                            <thead class="thead-dark">
                                                <tr>
                                                    <th>Фото</th>
                                                    <th>Имя</th>
                                                    <th>Тип</th>
                                                    <th>Комментарии</th>
                                                </tr>
                                            </thead>
                                            <tbody class="align-middle">
                                                    {% for item in user_items %}
                                                    <tr>
                                                        <td  class="align-middle"><img src="{% if item.get_first_photo %}{{ item.get_first_photo }}{% else %}{% static 'img/default_item.jpg' %}{% endif %}" alt="" style="width: 50px;"></td>
                                                        <td class="align-middle"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
                                                        <td class="align-middle">{{ item.type }}</td>
                                                        <td class="align-middle">{{ item.comments.count }}</td>
                                                        
                                                    </tr>
                                                    {% endfor %}
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="tab-pane-2">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <h4 class="mb-4">{{ user.to_user.count }} Отзывы "{{ user.username }}"</h4>
                                                <div class="pre-scrollable" >
            {% for comment in user.to_user.all %}
            
                                                <div class="media mb-4">
                                                    <img src="{% if comment.user.image %} {{ comment.user.image.url }}{% else %} {% static 'img/default_avatar.jpg' %} {% endif %}" alt="Image" class="img-fluid1 mr-3 mt-1" style="width: 45px;">
                                                    <div class="media-body">
                                                        <h6>{{ comment.from_user.username }}<small> - <i>{{ comment.created }}</i>{% if request.user == comment.from_user %} <a href="{% url "users:delete_comment" comment_id=comment.id  %}" class="btn-danger" >Удалить</a>{% endif %}</small></h6>
            
                                                        <p>{{comment.body}}</p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <h4 class="mb-4">Оставить отзыв</h4>
                                                <small>Ваш email адрес не будет опубликован. Поле отмечено *</small>
                                                {% if user.is_authenticated %}                                    
                                                <form method="post" >
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        <label for="message">Оставить отзыв *</label>
                                                        <textarea name="user_review" id="message" cols="30" rows="5" class="form-control"></textarea>
                                                    </div>
                                                    <div class="form-group mb-0">
                                                        <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                                    </div> 
                                                </form>
                                                {% else %}
                                                <a href="{% url 'users:login' %}" class="btn btn-primary px-3">Зайдите чтобы оставить отзыв</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Обмены</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pt-3 pb-2">
        
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Активные обмены</h6>
                            <h6 class="font-weight-medium">{{ user.active_deals }}</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Количество обменов</h5>
                            <h5>{{ user.amount_of_deals }}</h5>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Checkout End -->

{% endblock %}

user/templates/user/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Foodeiblog Template">
    <meta name="keywords" content="Foodeiblog, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Unna:400,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}" type="text/css">
</head>

<body class="fixed-position">
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Sign In Section Begin -->
    <div class="signin">
        <div class="signin__warp">
            <div class="signin__content">
                <div class="signin__logo">
                    <a href="#"><img src="{% static 'img/siign-in-logo.png' %}" alt=""></a>
                </div>
                
                <div class="signin__form">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            {% url 'users:registration' as reg %}
                            <a data-toggle="tab" href="{% url 'users:registration' %}" role="tab" aria-selected="false">
                                <a class="nav-link {% if request.path != reg %}active {% endif %}" href="{% url 'users:registration' %}"> Sign up </a>
                            </a>
                        
                        </li>
                        <li class="nav-item">
                            {% url 'users:login' as log %}
                            <a  data-toggle="tab" href="{% url 'users:login' %}" role="tab" aria-selected="false">
                                <a class="nav-link {% if request.path != log %}active {% endif %}" href="{% url 'users:login' %}"> Sign in </a>
                            </a>
                        
                        </li>
                        <li class="nav-item">
                    </ul> 
                    <div class="tab-content">
                        {% url 'users:registration' as reg %}
                        <div class="tab-pane {% if request.path == reg %}active {% endif %}" id="tabs-1" role="tabpanel">
                            <div class="signin__form__text">
                                <p>Войти через аккаунт :</p>
                                <div class="signin__form__signup__social">
                                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                                    <a href="#" class="google"><i class="fa fa-google"></i></a>
                                </div>
                                <div class="divide">или</div>
                                {% if reg_form.errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                    style="margin-top: 50px;">
                                    {{ reg_form.errors }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endif %}
                                <form action="{% url 'users:registration' %}" method="post">
                                    {% csrf_token %}
                                    {{ reg_form.username }}
                                    {{ reg_form.email }}
                                    {{ reg_form.password1 }}
                                    {{ reg_form.password2 }}
                                    {{ reg_form.first_name }} {{ reg_form.last_name }}
                                    <label for="sign-agree-check">
                                        я согласен с условиями пользовательского соглашения
                                        <input type="checkbox" id="sign-agree-check">
                                        <span class="checkmark"></span>
                                    </label>
                                    <button type="submit" class="site-btn">Регистрация</button>
                                </form>
                            </div>
                        </div>
                        {% url 'users:login' as log %}
                        <div class="tab-pane {% if request.path == log %}active {% endif %}" id="tabs-2" role="tabpanel">
                            <div class="signin__form__text">
                                <p>Войти через аккаунт :</p>
                                <div class="signin__form__signup__social">
                                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                                    <a href="#" class="google"><i class="fa fa-google"></i></a>
                                </div>
                                <div class="divide">или</div>
                                {% if messages or login_form.non_field_errors %}
                        <div class="alert
                        {% if messages %} alert-success {% else %} alert-warning {% endif %}
                        alert-dismissible fade show" role="alert"
                            style="margin-top: 50px;">
                            {% if messages %}
                            {% for message in messages %}
                            {{ message }}
                            {% endfor %}
                            {% else %}
                            {{ login_form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    {{ login_form.username }}
                                    {{ login_form.password }}
                                    <button type="submit" class="site-btn">Логин</button>
                                </form>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/log.js' %}"></script>
</body>
</html>