catalog/urls.py
from django.urls import path
from .views import *


app_name = 'catalog'


urlpatterns = [
    path('', shop, name='shop'),
    path('like/<int:item_id>/', like_item, name='like_item'),
    path('favorite/<int:item_id>/', favorite_item, name='favorite_item'),
    path('exchange/<int:received_item_id>/', exchange, name='exchange'),
    path('send_offer/<int:received_item_id>/<int:sent_item_id>/', send_exchange, name='send_offer'),
    path('<slug:item_slug>/<int:item_id>/', item_detail, name='item_detail'),
    path('add_item/', add_item, name='add_item'),
    path('delete_item/<int:obj_id>', delete_obj, name='delete_item'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('change_exchange/<int:exchange_id>/<str:action>', change_exchange, name='change_exchange'),
    path('add_message/', contact, name='add_message'),
    path('search/', search_view, name='search'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:room_name>/', views.chat_room, name='chat_room'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from catalog.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('user.urls', namespace='users')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import *


app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user-profile/<str:username>/<int:user_id>/', user_details, name='user_profile'),
    path('add_comment/<int:user_id>/', add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('positive/<int:user_id>', user_positive_rating, name='positive_rating'),
    path('negative/<int:user_id>', user_negative_rating, name='negative_rating'),
    path('logout/', logout, name='logout'),

]

templates/base.html
{% load static %}
{% load shoptags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>SwopShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-heart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="{% url 'index' %}" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">Swop</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                </a>
            </div>
            <div class="col-lg-4 col-6 text-left">
                <form action="{% url 'catalog:search' %}">
                    <div class="input-group">
                        <input name="q"  type="text" class="form-control" placeholder="Поиск">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">Обратная связь</p>
                <h5 class="m-0">+012 345 6789</h5>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                    <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Категории</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                    <div class="navbar-nav w-100">
                        {% all_categories as categories %}
                        {% for category in categories %}
                        <a href="{% url 'catalog:shop' %}?{% change_params category=category.id  %}" class="nav-item nav-link">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                        <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            {% comment %} <a href="{% url 'index' %}" {% if request.resolver_match.view_name == 'index' %} class="nav-item nav-link active"{% else %} class="nav-item nav-link"{% endif %}>Главная страница</a> {% endcomment %}
                            <a href="{% url 'catalog:shop' %}" {% if request.resolver_match.view_name == 'catalog:shop' %} class="nav-item nav-link active"{% else %} class="nav-item nav-link"{% endif %}>Каталог</a>
                            <a href="{% url 'catalog:add_message' %}"{% if request.resolver_match.view_name == 'catalog:add_message' %} class="nav-item nav-link active"{% else %} class="nav-item nav-link"{% endif %}>Контакт</a>
                            {% if user.is_authenticated %}
                            <a href="{% url 'catalog:add_item' %}"{% if request.resolver_match.view_name == 'catalog:add_item' %} class="nav-item nav-link active"{% else %} class="nav-item nav-link"{% endif %}>Добавить Лот</a>
                            {% endif %}
                            {% if user.is_superuser %}
                            <a href="{% url 'admin:index' %}" class="nav-item nav-link">Админ панель</a>
                            {% endif %}
                        </div>
                        {% if user.is_authenticated %}
                        <button type="button" id="acc_btn" value="{{ request.user.username }}" class="nav-item nav-link" data-toggle="dropdown">{{ request.user.username }}</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{% url 'users:profile' %}" type="button">Профиль</a>
                            <a class="dropdown-item" href="{% url 'users:logout' %}" type="button">Выйти</a>
                            {% else %}
                            <button type="button" class="nav-item nav-link" data-toggle="dropdown">Аккаунт</button>
                            <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{% url 'users:login' %}" type="button">Логин</a>
                            <a class="dropdown-item" href="{% url 'users:registration' %}" type="button">Регистрация</a>
                            {% endif %}
                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

{% block content %} {% endblock %}



    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://github.com/Nimblen">NimBLen</a>
                    <br>Distributed By: <a href="https://github.com/Nimblen" target="_blank">NimBLen</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid1" src="{% static 'img/payments.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    {% block include_js %}
    {% endblock %}
    <script>document.addEventListener('DOMContentLoaded', (event) => {
        // DOM loaded
        {% block domready %}
        {% endblock %}
    })</script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load shoptags %}

{% block content %}
<!-- Новая секция с особенностями -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3 text-center">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="bg-light shadow-sm rounded p-4 mb-4">
                <h1 class="fa fa-check text-primary mb-3"></h1>
                <h5 class="font-weight-semi-bold">Качественный продукт</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="bg-light shadow-sm rounded p-4 mb-4">
                <h1 class="fa fa-shipping-fast text-primary mb-3"></h1>
                <h5 class="font-weight-semi-bold">Бесплатная доставка</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="bg-light shadow-sm rounded p-4 mb-4">
                <h1 class="fas fa-exchange-alt text-primary mb-3"></h1>
                <h5 class="font-weight-semi-bold">Прямой обмен</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="bg-light shadow-sm rounded p-4 mb-4">
                <h1 class="fa fa-phone-volume text-primary mb-3"></h1>
                <h5 class="font-weight-semi-bold">Поддержка 24/7</h5>
            </div>
        </div>
    </div>
</div>

<!-- Раздел приветствия -->
<div class="container-fluid pt-5">
    <h2 class="section-title text-uppercase text-center mb-4"><span class="bg-secondary text-primary px-3 py-2 rounded">Добро пожаловать на наш сайт обмена товаров и услуг!</span></h2>
    <div class="row px-xl-5 pb-3 text-center">
        <div class="col-12">
            <p class="lead">Здесь вы можете зарегистрироваться, создать личный профиль и опубликовать объявление с описанием того, что хотите обменять.</p>
            <p class="lead">Просматривайте объявления других пользователей, оставляйте комментарии и предложения по обмену.</p>
            <p class="lead">Договаривайтесь о деталях обмена, обменивайтесь товарами или услугами, либо договаривайтесь о доставке товаров.</p>
            <p class="lead">Оценивайте других пользователей и их объявления, чтобы создать доверительные отношения.</p>
        </div>
    </div>
</div>


<!-- Раздел последних объявлений -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title text-uppercase text-center mb-4"><span class="bg-secondary text-primary px-3 py-2 rounded">Последние объявления</span></h2>
    <div class="row px-xl-5"> 
        {% if user.is_authenticated %}
        {% get_latest_items user=user as latest_items %}
        {% else %}
        {% get_latest_items as latest_items %}
        {% endif %}
        {% if latest_items %}
        {% for item in latest_items %}
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <div class="product-item bg-light shadow-sm rounded mb-4">
                <div class="product-img position-relative overflow-hidden rounded-top">
                    <img class="img-fluid w-100" src="{% if item.images.all %}{{ item.get_first_photo }}{% else %}{% static 'img/default_item.jpg' %}{% endif %}" alt="">
                    {% if user.is_authenticated %}
                    <div class="product-action">
                        {% if request.user in item.likes.all %}
                        <a class="btn btn-outline-dark btn-square " href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="fa fa-heart "></i></a>
                        {% else %}
                        <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="far fa-heart"></i></a>
                        {% endif %}
                        <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:exchange' received_item_id=item.id  %}"><i class="fa fa-sync-alt"></i></a>
                        {% if request.user in item.favorites.all %}
                        <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="fa fa-star"></i></a>
                        {% else %}
                        <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="far fa-star"></i></a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                <div class="text-center py-4">
                    <a class="h6 text-decoration-none text-truncate" href="{{ item.seller.get_absolute_url }}">{{ item.seller }}</a>
                    <div class="d-flex align-items-center justify-content-center mt-2">
                        <a class="h5 text-decoration-none text-truncate" href="{{ item.get_absolute_url }}">{{item.name}}</a>
                    </div>
                    <small>likes: {{ item.total_likes }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-12">
            <div class="text-center py-4">
                <div class="h6 text-decoration-none text-truncate">Нет новых объявлений</div>
            </div>
        </div>
        {% endif %}
    </div>
</div>




<!-- Раздел с контактной информацией -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title text-uppercase text-center mb-4"><span class="bg-secondary text-primary px-3 py-2 rounded">Контактная информация</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-4 mb-5">
            <h5 class="font-weight-bold text-primary mb-3">Адрес</h5>
            <p>123 Улица, Город, Страна</p>
        </div>
        <div class="col-lg-4 mb-5">
            <h5 class="font-weight-bold text-primary mb-3">Email</h5>
            <p>info@example.com</p>
        </div>
        <div class="col-lg-4 mb-5">
            <h5 class="font-weight-bold text-primary mb-3">Телефон</h5>
            <p>+012 345 6789</p>
        </div>
    </div>
</div>
{% endblock %}