catalog/urls.py
from django.urls import path
from .views import *


app_name = 'catalog'


urlpatterns = [
    path('', shop, name='shop'),
    path('like/<int:item_id>/', like_item, name='like_item'),
    path('favorite/<int:item_id>/', favorite_item, name='favorite_item'),
    path('exchange/<int:received_item_id>/', exchange, name='exchange'),
    path('send_offer/<int:received_item_id>/<int:sent_item_id>/', send_exchange, name='send_offer'),
    path('<slug:item_slug>/<int:item_id>/', item_detail, name='item_detail'),
    path('add_item/', add_item, name='add_item'),
    path('delete_item/<int:obj_id>', delete_obj, name='delete_item'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('change_exchange/<int:exchange_id>/<str:action>', change_exchange, name='change_exchange'),
    path('add_message/', contact, name='add_message'),
    path('search/', search_view, name='search'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:room_name>/', views.chat_room, name='chat_room'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from catalog.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('user.urls', namespace='users')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('__debug__/', include('debug_toolbar.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import *


app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('user-profile/<str:username>/<int:user_id>/', user_details, name='user_profile'),
    path('add_comment/<int:user_id>/', add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>', delete_comment, name='delete_comment'),
    path('positive/<int:user_id>', user_positive_rating, name='positive_rating'),
    path('negative/<int:user_id>', user_negative_rating, name='negative_rating'),
    path('logout/', logout, name='logout'),

]

catalog/models.py
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField
from user.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from="name")
    active = models.BooleanField(default=True)
    description = models.TextField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    deactivate_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=0)
    choices = (("service", "Услуга"), ("item", "Вещь"))
    type = models.CharField(max_length=10, choices=choices, default="item")
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    favorites = models.ManyToManyField(User, related_name="favorites", blank=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("catalog:item_detail", args=[self.slug, self.pk])

    def get_first_photo(self):
        if self.images:
            try:
                return self.images.all()[0].photo.url
            except IndexError:
                return None
        else:
            return None

    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Comment by {} on {}".format(self.user, self.item)


class Photo_of_item(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="images")
    photo = models.ImageField(upload_to="photos")

    def __str__(self) -> str:
        return self.item.name


class Exchange(models.Model):
    STATUS_CHOICES = (
        ("waiting", "Ожидание владельца"),
        ("processing", "В процессе"),
        ("complete", "Завершен"),
    )

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=0)
    received_item = models.ForeignKey(
        Item, null=True, on_delete=models.SET_NULL, related_name="received_item"
    )
    sent_item = models.ForeignKey(
        Item, null=True, on_delete=models.SET_NULL, related_name="sent_item"
    )
    start_exchange = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=255, blank=True, null=True)


class Message(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    user = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Message by {self.user}"


class Visit(models.Model):
    user = models.CharField(max_length=30, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

catalog/forms.py
from unicodedata import category
from django import forms
from .models import Message, Item, Category, Photo_of_item


class AddMessageForm(forms.Form):
    name = forms.CharField(
        max_length=80,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Введите имя"}
        ),
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Введите почту"}
        )
    )
    subject = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Введите название темы"}
        ),
    )
    body = forms.Textarea(
        attrs={"class": "form-control", "placeholder": "Введите сообщение"}
    )

    class Meta:
        model = Message
        fields = ("name", "email", "subject", "body")


class AddItemForm(forms.ModelForm):
    name = forms.CharField(
        max_length=80,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Введите название"}
        ),
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Введите описание"}
        )
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={"class": "custom-select"}),
    )
    choices = (("service", "Услуга"), ("item", "Вещь"))
    type = forms.ChoiceField(choices=choices, initial="item")

    class Meta:
        model = Item
        fields = ("name", "description", "category", "type")


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo_of_item
        fields = ["photo"]


PhotoFormSet = forms.inlineformset_factory(
    Item,
    Photo_of_item,
    form=PhotoForm,
    extra=3,
    can_delete=False,
)

catalog/views.py
from unicodedata import category
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from user.models import User
from .utils.services import paginate_objects, del_item
from .models import Comment, Item, Photo_of_item, Exchange
from .forms import AddMessageForm, AddItemForm, PhotoFormSet
# Create your views here.


def index(request):
    return render(request, "index.html")


def shop(request):
    category = request.GET.get("category", None)
    page = request.GET.get("page", 1)
    sort_by = request.GET.get("sort_by", "-date")
    type_by = request.GET.get("type_by", "all")
    per_page = request.GET.get("per_page", 9)
    items = Item.objects.filter(active=True)
    if category:
        items = items.filter(category=category)
    my_lots = []
    if request.user.is_authenticated:
        my_lots = items.filter(seller=request.user)[:3]
        items = items.exclude(seller=request.user)
    if type_by != "all":
        items = items.filter(type=type_by)
    paginated_items = paginate_objects(items, page, per_page, sort_by)
    context = {"items": paginated_items, "my_lots": my_lots}
    return render(request, "catalog/shop.html", context)


def like_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    if request.user in item.likes.all():
        item.likes.remove(request.user)
    else:
        item.likes.add(request.user)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

def favorite_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    if request.user in item.favorites.all():
        item.favorites.remove(request.user)
    else:
        item.favorites.add(request.user)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

def item_detail(request, item_slug, item_id):
    item = get_object_or_404(Item, slug=item_slug, pk=item_id)
    items_by_category = Item.objects.filter(category__name=item.category, active=True).exclude(id=item.id)
    if request.user.is_authenticated:
        items_by_category.exclude(seller=request.user)
    photos_of_items = Photo_of_item.objects.filter(item=item)
    if request.method == "POST" and request.user.is_authenticated:
        review = request.POST.get("review")
        if review:
            Comment.objects.create(user=request.user, item=item, body=review)
            messages.success(request, "Ваше отзыв доставлено")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    context = {"item": item, "photos_of_items": photos_of_items, "items_by_category": items_by_category}
    return render(
        request,
        "catalog/item_detail.html",
        context,
    )


@login_required
def add_item(request):
    if request.method == "POST":
        form = AddItemForm(data=request.POST)
        formset = PhotoFormSet(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            item = form.save(commit=False)
            item.seller = request.user
            item.save()
            for f in formset:
                if f.cleaned_data:
                    photo = f.save(commit=False)
                    photo.item = item
                    photo.save()
            return HttpResponseRedirect(reverse("catalog:shop"))
    form = AddItemForm()
    formset = PhotoFormSet()
    context = {"form": form, "formset": formset}
    return render(request, "catalog/add_item.html", context)


@login_required
def exchange(request, received_item_id):
    si_id = request.GET.get("SI_id", None)
    sent_item = None
    if si_id:
        sent_item = get_object_or_404(Item, pk=si_id)
        if sent_item.seller != request.user:
            sent_item = None
    received_item = get_object_or_404(Item, pk=received_item_id)
    sent_items_list = Item.objects.filter(seller=request.user, active=True)
    context = {
        "received_item": received_item,
        "sent_items": sent_items_list,
        "sent_item": sent_item,
    }
    return render(request, "catalog/exchange.html", context)


@login_required
def send_exchange(request, received_item_id, sent_item_id):
    sent_item = get_object_or_404(Item, pk=sent_item_id)
    received_item = get_object_or_404(Item, pk=received_item_id)
    if request.method == "POST":
        message = request.POST.get("message", "")
        try:
            Exchange.objects.create(
                sent_item=sent_item,
                received_item=received_item,
                status="waiting",
                message=message,
            )
            messages.success(request, "Отправлено")
            return HttpResponseRedirect(reverse("users:profile"))
        except IntegrityError:
            messages.error(request, "Ошибка: обмен уже отправлен")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def change_exchange(request, exchange_id, action):
    exchange = get_object_or_404(Exchange, pk=exchange_id)
    
    if action == "accept":
        accept_exchange(request, exchange)
    if action == "del":
        if exchange.status == "processing":
            decrease_active_deals(exchange.sent_item.seller)
            decrease_active_deals(exchange.received_item.seller)
        delete_exchange(exchange)
        

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

def accept_exchange(request, exchange):
    if exchange.status == "waiting":
        exchange.status = "processing"
        exchange.save()
        increase_active_deals(exchange.sent_item.seller)
        increase_active_deals(exchange.received_item.seller)
    elif exchange.status == "processing":
        exchange.status = "complete"
        exchange.save()
        del_item(exchange.sent_item)
        del_item(exchange.received_item)
        decrease_active_deals(exchange.sent_item.seller)
        decrease_active_deals(exchange.received_item.seller)

def delete_exchange(exchange):
    exchange.delete()

def increase_active_deals(user):
    user.active_deals += 1
    user.amount_of_deals += 1
    user.save()

def decrease_active_deals(user):
    user.active_deals -= 1
    user.save()

@login_required
def delete_obj(request, obj_id):
    obj = get_object_or_404(Item, pk=obj_id)
    if obj.seller == request.user:
        del_item(obj)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def delete_comment(request, comment_id):
    obj = get_object_or_404(Comment, pk=comment_id)
    if obj.user == request.user:
        obj.delete()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def contact(request):
    if request.method == "POST":
        comment_form = AddMessageForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.user = request.user
            comment_form.save()
            messages.success(request, "Ваше сообщение доставлено")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    comment_form = AddMessageForm()
    context = {"form": comment_form}
    return render(request, "catalog/contact.html", context)


def search_view(request):
    page = request.GET.get("page", 1)
    sort_by = request.GET.get("sort_by", "-date")
    type_by = request.GET.get("type_by", "all")
    per_page = request.GET.get("per_page", 9)
    word = request.GET.get("q")
    items = None
    users = None
    if word:
        items = Item.objects.filter(name__iregex=word)
        if type_by != "all":
            items = items.filter(type=type_by)
        paginated_items = paginate_objects(items, page, per_page, sort_by)

        users = User.objects.filter(
            Q(first_name__iregex=word) | Q(last_name__iregex=word)
        )

    context = {
        "title": "Результаты поиска",
        "found_items": paginated_items,
        "found_users": users,
    }

    return render(request, "catalog/search_result.html", context)

catalog/templates/catalog/add_item.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="{% url 'index' %}">Домой</a>
                <a class="breadcrumb-item text-dark" href="{% url 'catalog:shop' %}">Каталог</a>
                <span class="breadcrumb-item active">Добавть Лот</span>
            </nav>
        </div>
    </div>
</div>



    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary text-primary pr-3">Добавить Лот</span></h2>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5"> 
                <div class="contact-form bg-light p-30">

                    {% comment %} <div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button><strong> {{ error }} </div> {% endcomment %}
                        
                    <form action="{% url 'catalog:add_item' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="control-group">
                            <label>Название Лота</label>
                            {{ form.name }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <label>Категория</label>
                            {{ form.category}}
                    <p class="help-block text-danger"></p>
                    </div>
                        <div class="control-group">
                            <label>Описание</label>
                            {{ form.description }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <label>Тип</label>
                            {{ form.type }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" >Добавить 
                                Лот</button>
                        </div>
                    
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <div class="bg-light p-30 mb-30">
                    {{ formset.management_form }}
                    {% for form in formset %}
                    <div class="fa-file-upload">{{ form }}</div>
                    {% endfor %}
                </div>
            </form>
                <div class="bg-light p-30 mb-3">
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/item_detail.html
{% extends "base.html" %}
{% load static %}
{% load shoptags %}
{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'index' %}">Домой</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'catalog:shop' %}">Каталог</a>
                    <span class="breadcrumb-item active">{{item.name}}</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        {% if photos_of_items.count > 0 %}
                        {% for photo in photos_of_items %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img class="w-100 h-100" src="{{ photo.photo.url }}" alt="{{ photo.name }}">
    </div>
    {% endfor %}
    {% else %}
    <div class="carousel-item active">
        <img class="w-100 h-100" src="{% static 'img/default_item.jpg' %}" alt="{{ photo.name }}">
    </div>
    {% endif %}
                    </div>
                    {% if photos_of_items.count > 1 %}
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                    {% endif %}
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{ item.name }}</h3>
                    <div class="d-flex mb-3">
                        <div id="sellerInfo" class="text-primary mr-2">
                            <a href="{{ item.seller.get_absolute_url }}"> {{item.seller}} </a>
                        </div>
                        
                    </div>
                    <small class="h6 text-decoration-none text-truncate">рейтинг пользователя:{{item.seller.user_rating}}</small><br>
                    <small class="h6 text-decoration-none text-truncate">количество дел: {{item.seller.amount_of_deals}}</small><br>
                    <small class="h6 text-decoration-none text-truncate">тип: {{item.type}}</small><br>
                    <i class="far fa-heart"></i><span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">{{item.total_likes}}</span>
                    <p class="mb-4">{{ item.description }}</p>
                    <div class="d-flex align-items-center mb-4 pt-2">
                        <div class="input-group quantity mr-3" style="width: 130px;">
                        <button class="btn btn-primary px-3" id="openChat" >Открыть чат</button>
                        </div>
                        {% if request.user != item.seller and user.is_authenticated %}
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            <a href="{% url 'catalog:exchange' received_item_id=item.id  %}"  class="btn btn-primary px-3"><i class="fa fa-sync-alt"></i> Предложить обмен </a>
                        </div>
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            {% if request.user in item.likes.all %}
                                    <a class="btn btn-outline-dark btn-square " href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="fa fa-heart "></i></a>
                                    {% else %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="far fa-heart"></i></a>
                                    {% endif %}
                                    {% if request.user in item.favorites.all %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="fa fa-star"></i></a>
                                    {% else %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="far fa-star"></i></a>
                                    {% endif %}
                            </div>
                        {% elif request.user != item.seller %}
                        <a href="{% url 'users:login' %}" class="btn btn-primary px-3">Зайти в аккаунт чтобы предложить обмен</a>
                        {% endif %}
                    </div>
                    <div class="d-flex pt-2">
                        <strong class="text-dark mr-2">поделится:</strong>
                        <div class="d-inline-flex">
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="text-dark px-2" href="/chat/${roomName}/">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-pinterest"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
            <div class="col">
                <div class="bg-light p-30">
                        <div class="tab-pane fade show active" id="tab-pane-3">
                            <div class="row">
                                <div class="col-md-6">
                                    <h4 class="mb-4">{{ item.comments.count }} Отзыв  "{{ item.name }}"</h4>
                                    <div class="pre-scrollable" >
{% for comment in item.comments.all %}

                                    <div class="media mb-4">
                                        <img src="{% if comment.user.image %} {{ comment.user.image.url }}{% else %} {% static 'img/default_avatar.jpg' %} {% endif %}" alt="Image" class="img-fluid1 mr-3 mt-1" style="width: 45px;">
                                        <div class="media-body">
                                            <h6>{{ comment.user.username }}<small> - <i>{{ comment.created }}</i>{% if request.user == comment.user %} <a href="{% url "catalog:delete_comment" comment_id=comment.id  %}" class="btn-danger" >delete</a>{% endif %}</small></h6>

                                            <p>{{comment.body}}</p>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <h4 class="mb-4">Оставить отзыв</h4>
                                    <small>Ваш email адрес не будет опубликован. Поле отмечено *</small>
                                    {% if user.is_authenticated %}                                    
                                    <form method="post" >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="message">Ваш отзыв *</label>
                                            <textarea name="review" id="message" cols="30" rows="5" class="form-control"></textarea>
                                        </div>
                                        <div class="form-group mb-0">
                                            <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                        </div> 
                                    </form>
                                    {% else %}
                                    <a href="{% url 'users:login' %}" class="btn btn-primary px-3">Зайти чтобы оставить отзыв</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    <!-- Shop Detail End -->


    <!-- Products Start -->
    <div class="container-fluid py-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Вам может понравится</span></h2>
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel related-carousel">
                    {% for item in items_by_category %}
                        <div class="product-item bg-light mb-4">
                            <div class="product-img position-relative overflow-hidden">
                                <img class="img-fluid" src="{% if item.images.all %}{{ item.get_first_photo }}{% else %}{% static 'img/default_item.jpg' %}{% endif %}" alt="">
                                {% if user.is_authenticated %}
                                <div class="product-action">
                                    {% if request.user in item.likes.all %}
                                    <a class="btn btn-outline-dark btn-square " href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="fa fa-heart "></i></a>
                                    {% else %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:like_item' item_id=item.id  %}"><i class="far fa-heart"></i></a>
                                    {% endif %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:exchange' received_item_id=item.id  %}"><i class="fa fa-sync-alt"></i></a>
                                    {% if request.user in item.favorites.all %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="fa fa-star"></i></a>
                                    {% else %}
                                    <a class="btn btn-outline-dark btn-square" href="{% url 'catalog:favorite_item' item_id=item.id  %}"><i class="far fa-star"></i></a>
                                    {% endif %}
                                </div>
                                {% endif %}
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="">{{ item.seller }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <a class="h5 text-decoration-none text-truncate" href="{{ item.get_absolute_url }}">{{item.name}}</a>
                                </div>
                            </div>
                        </div>
                    
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('openChat').addEventListener('click', function() {
            var chatWindow = window.open('/chat/' + {{item.id}} + '/', 'Chat Window', 'width=800, height=700');
            
        });
        
    </script>

{% endblock %}